name: Lint and Typecheck
run-name: "Linting and Typechecking your code! 🚀"

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Linting (ESLint and Prettier)
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setep Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 'latest'

        - name: Install dependencies
          run: npm ci

        - name: Run lint
          run: npm run lint
  
  type-check:
    name: Type Checks (TypeScript)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
      
      - name: Install dependencies
        run: npm ci

      - name: Typecheck code
        run: npm run type-check